IF OBJECT_ID ( 'msp_AccountInsert', 'P' ) IS NOT NULL   
    DROP PROCEDURE msp_AccountInsert;  
GO  

CREATE PROCEDURE [dbo].[msp_AccountInsert]
	@AccountID INT,
	@AccountName VARCHAR(255)

AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED	

DECLARE @TranStarted bit

BEGIN TRY
	
	/* START AN EXPLICIT TRANSACTION IF THERE ISNT ONE ALREADY */
	IF @@TRANCOUNT = 0
	BEGIN
		SET @TranStarted = 1
		BEGIN TRAN
	END
	
	INSERT INTO [dbo].[Account]
	(AccountID, AccountName)
	SELECT @AccountID, @AccountName
	
	/* COMMIT THE EXPLICIT TRANSACTION IF THERE ONE WAS STARTED VIA THIS PROCEDURE */
	IF @TranStarted = 1
		COMMIT TRAN

END TRY
BEGIN CATCH

	/* ONLY ATTEMPT TO ROLLBACK THE TRAN IF I STARTED ONE */
	IF @TranStarted = 1
		ROLLBACK TRAN

	EXEC usp_GetErrorInfo;

END CATCH

GO